# Generated by Django 4.2.7 on 2023-11-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enter_Info',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=122)),
                ('age', models.IntegerField()),
                ('work_class', models.CharField(max_length=122)),
                ('marital_status', models.CharField(max_length=122)),
                ('occupation', models.CharField(max_length=122)),
                ('gender', models.CharField(max_length=122)),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
