# Generated by Django 4.2.7 on 2023-11-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Retirement_Industry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enter_info',
            name='password',
            field=models.CharField(default=123456, max_length=122),
            preserve_default=False,
        ),
    ]
