# Generated by Django 4.2.7 on 2023-11-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Retirement_Industry', '0002_enter_info_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction_History',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('person_id', models.IntegerField()),
                ('transaction_name', models.CharField(max_length=122)),
                ('transaction_amount', models.IntegerField()),
                ('expense_category', models.CharField(max_length=122)),
                ('rounded_off_amount', models.IntegerField()),
            ],
        ),
    ]
