# Generated by Django 4.2.7 on 2023-11-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Retirement_Industry', '0003_transaction_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='enter_info',
            name='mail',
            field=models.EmailField(default='me@gmail.com', max_length=254),
        ),
    ]
