# Generated by Django 4.2.7 on 2023-11-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Retirement_Industry', '0004_enter_info_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enter_info',
            name='age',
            field=models.CharField(max_length=122),
        ),
    ]
