# Generated by Django 4.2.7 on 2023-11-26 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Retirement_Industry', '0006_current_investments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Current_Investments',
            new_name='Current_Investment',
        ),
    ]
