# Generated by Django 4.2.7 on 2023-11-26 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Retirement_Industry', '0007_rename_current_investments_current_investment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enter_Info',
            new_name='Profile_Info',
        ),
    ]
