# Generated by Django 4.2.7 on 2023-11-26 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Retirement_Industry', '0008_rename_enter_info_profile_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='current_investment',
            name='date_of_investment',
            field=models.CharField(default=1, max_length=122),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='current_investment',
            name='investment_amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='current_investment',
            name='person_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='current_investment',
            name='policy_term',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='current_investment',
            name='rate_of_interest',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='current_investment',
            name='scheme_name',
            field=models.CharField(default=1, max_length=122),
            preserve_default=False,
        ),
    ]
