# Generated by Django 6.0.2 on 2026-07-21 06:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Retirement_Industry', '0009_current_investment_date_of_investment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeEarned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.IntegerField()),
                ('badge_key', models.CharField(max_length=60)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BehaviorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.IntegerField()),
                ('archetype', models.CharField(default='', max_length=60)),
                ('traits_json', models.TextField(default='{}')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChallengeProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.IntegerField()),
                ('challenge_key', models.CharField(max_length=60)),
                ('status', models.CharField(default='active', max_length=12)),
                ('progress', models.IntegerField(default=0)),
                ('target', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GamificationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.IntegerField()),
                ('xp', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('streak_days', models.IntegerField(default=0)),
                ('last_active', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.IntegerField()),
                ('name', models.CharField(max_length=122)),
                ('emoji', models.CharField(default='🎯', max_length=8)),
                ('target_amount', models.IntegerField()),
                ('target_months', models.IntegerField(default=0)),
                ('saved_amount', models.IntegerField(default=0)),
                ('tier', models.CharField(default='major', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SavingsLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('multiplier', models.FloatField(default=1.0)),
                ('reason', models.CharField(default='', max_length=122)),
                ('goal_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile_info',
            name='city',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='profile_info',
            name='debt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile_info',
            name='existing_investments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile_info',
            name='fixed_expenses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile_info',
            name='monthly_savings_goal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile_info',
            name='risk_appetite',
            field=models.CharField(default='Medium', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction_history',
            name='is_impulse',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction_history',
            name='is_subscription',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction_history',
            name='merchant',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='transaction_history',
            name='source',
            field=models.CharField(default='Manual', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction_history',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
