# Generated by Django 6.0.2 on 2026-07-21 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Retirement_Industry', '0010_badgeearned_behaviorprofile_challengeprogress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_info',
            name='mail',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
